Add homework_02
valentinvarbanov/software_engineering_2021 pull request #17
Opened 2021-10-31 01:03 UTC by mvvrachev

2021-11-03 15:28 UTC, Alexander1022 approved these changes
I am approving this homework! Good job!

2021-11-03 16:10 UTC, StelianRBG requested changes
Good job but i have small remarks. Please try to solve some of them!

2021-11-03 16:10 UTC, StelianRBG commented on homework_02/_12_Martin_Vrachev/views.py
> +    params = {
If you want take departure time you can add in 'included': 'schedule'

2021-11-03 16:10 UTC, StelianRBG commented on homework_02/_12_Martin_Vrachev/templates/departure_board.html
> +            <td>{{ r.attributes.departure_time }}</td>
Yo cant directly take departure time because it some times is None you cant take it from schedule

2021-11-03 16:10 UTC, StelianRBG commented on homework_02/_12_Martin_Vrachev/templates/departure_board.html
> +            <td>{{ r.attributes.arrival_time }}</td>
You dont need arrival time

2021-11-03 16:22 UTC, StelianRBG commented on homework_02/_12_Martin_Vrachev/views.py
> +    time = now.strftime('%l:%M %p')
%I (i) not %l (L)

2021-11-09 14:48 UTC, StelianRBG approved these changes

2021-11-09 14:51 UTC, merged