Victor Dimitrov homework
valentinvarbanov/software_engineering_2021 pull request #18
Opened 2021-10-31 13:20 UTC by Vic-Dim

2021-10-31 21:00 UTC, Martincho2003 requested changes
Add train# and make less requests.

2021-10-31 22:00 UTC, AngelStoyanov33 commented on homework_02/victor_dimitrov_04/admin.py
> +
Unused file - can be removed.

2021-10-31 22:01 UTC, AngelStoyanov33 commented on homework_02/victor_dimitrov_04/models.py
> +
Unused file - can be removed.

2021-10-31 22:06 UTC, AngelStoyanov33 requested changes

2021-10-31 22:06 UTC, AngelStoyanov33 commented on homework_02/victor_dimitrov_04/tests.py
> +
Unused file - can be removed.

2021-10-31 22:06 UTC, AngelStoyanov33 commented on homework_02/victor_dimitrov_04/views.py
> +        time_response = requests.get('https://api-v3.mbta.com/schedules', params=time_filters).json()
The "Schedules" object can be placed in the "includes" parameter instead of sending so many requests.

2021-10-31 22:06 UTC, AngelStoyanov33 commented on homework_02/victor_dimitrov_04/views.py
> +    data["context"] = trains
Train number missing

2021-10-31 22:06 UTC, AngelStoyanov33 commented on homework_02/victor_dimitrov_04/templates/index_trains.html
> +</html>
Nice and simple UI.

2021-11-02 15:55 UTC, Martincho2003 approved these changes
I think everything is fine now.

2021-11-02 15:55 UTC, Martincho2003 commented on homework_02/victor_dimitrov_04/templates/index_trains.html
> +            </tr>
Nice, you added it!

2021-11-02 15:55 UTC, Martincho2003 commented on homework_02/victor_dimitrov_04/views.py
> +    return render(request, "index_trains.html", data)
Now everything is added!

2021-11-02 16:39 UTC, AngelStoyanov33 commented on homework_02/victor_dimitrov_04/views.py
> +    data["context"] = trains
Train number added, good job.

2021-11-02 16:43 UTC, AngelStoyanov33 commented on homework_02/victor_dimitrov_04/views.py
> +        train_info['number'] = trip_id[10:14]
By using indexes, you limit the results. Imagine that we have more than 50. It's not a big deal, it works for this homework.

2021-11-02 16:45 UTC, AngelStoyanov33 approved these changes
It works and the requests sent count is now reduced. I've no further comments. Good job!

2021-11-02 16:46 UTC, merged